### ISSUE TITLE
It doesn't work with custom routes

### ISSUE THREAD

**Issue by JCKodel** [JakesMD/flutter_go_router_tabs#1]
My routes are defined as a custom class (i.e.: `final class SomeRoute extends GoRoute`). Also, that's the way go_router_builder works.

But there is a wrong type check in this package that throws a type cast exception:

https://github.com/JakesMD/flutter_go_router_tabs/blob/15ac32687242d56323070e22aff183bc87c9b082/lib/src/tab_shell_route.dart#L198

This will fail because `route.runtimeType` is `SomeRoute` in my case, not `GoRoute`.

The correct type checking should be `if(route is GoRoute)`.

**Comment by JakesMD** [comment]
Yep ok sorry. I'll fix it by tomorrow

**Comment by JakesMD** [comment]
Behind the scenes the TabShellRoute creates new GoRoutes in order to set the builder and page builder. It wouldn't create SomeRoute.

I admit I hadn't thought of this when designed the package which was a bit silly of me.

I think one way to fix this would be to make the routes list a `List<RouteBase> Function(builder, pageBuilder)`. This would require a breaking change.

Your code would then look something like this:
``` dart
TabShellRoute(
  routes: (builder, pageBuilder) {
    return [
      GoRoute(),
      SomeRoute(pageBuilder: pageBuilder);
    ]
  }
)
```

As I said I'll look into it as soon as I can. Thanks for submitting the issue! I'm sorry I saw it a bit late...

**Comment by JCKodel** [comment]
TBO, this package didn't work for me, I could not make it work in my setting.

But, that type checking is just plain wrong, and no break change will occur if you use

```dart
if (route is GoRoute) { 
```

`route`, in my case, is NEVER `GoRoute`. It is my custom route class OR shellroute.

**Comment by JakesMD** [comment]
0.3.0 now allows for custom GoRoutes or ShellRoutes or whatever. TabShellRoute no longer does any conversion behind the scenes so your SomeRoute will be conserved just as you define it.

In your case the code would look something like this:
``` dart
TabShellRoute(
  subPageBuilder: (context, state, direction, child) {
    return TabTransitionPage(
      key: state.pageKey,
      child: child,
      direction: direction,
      transitionsBuilder: TabTransitionPage.verticalSlideFadeTransition,
    );
  },
  routes: (subPageBuilder, direction) => [
    GoRoute(
      path: "/first",
      pageBuilder: (context, state) => subPageBuilder!(
        context,
        state,
        child: const FirstScreen(),
      ),
    ),
    SomeRoute(
      path: "/second",
      pageBuilder: (context, state) => subPageBuilder!(
        context,
        state,
        child: const SecondScreen(),
      ),
    ),
  ],
).toShellRoute,
```

I'm sorry the package didn't work for you. But thanks for submitting the issue all the same because now the package has improved quite a bit :)
